# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P52G2Js0rr0Bi_vleNcN2z9DxseAnIky
"""

first_name = str(input())
last_name = str(input())
Full_name = first_name + last_name
print(Full_name)


def string_alternative(name):
    result = '';
    length = len(name)
    for idx in range(length):
        if not idx % 2:
            result += name[idx]
    return result;


Str = "Good evening"
result = string_alternative(Str)
print(result)

def count_words(line, word_counts):
    words = line.split()
    # loop to count the occurance of each word
    for word in words:
        word_counts[word] = word_counts.get(word, 0) + 1
    return word_counts
# Main function
def main():
    input_filename = "input.txt"
    output_filename = "output.txt"

    try:
        # Reads the input file
        with open(input_filename, 'r') as input_file:
            readline = input_file.readlines()

        word_counts = {}
        for line in readline:
            line = line.strip()  # Remove leading/trailing whitespace
            # Function to count words
            word_count = count_words(line, word_counts)
        # Writing the input file lines to output file
        with open(output_filename, 'w') as output_file:
            for line in readline:
                output_file.write(line)

            output_file.write("\nWord_Count:\n")
            # Displaying the words and its count in output file
            for word, count in word_counts.items():
                output_file.write(f"{word}: {count}\n")
                print(f"{word}: {count}")

    except FileNotFoundError:
        print(f"File '{input_filename}' not found.")

if __name__ == "__main__":
    main()

data = input("enter customer heights : ")

def inchToCent(value):
    return value * 2.54

height = data.split()

new_list = []

for x in height:
    value = int(x)
    new_list.append(inchToCent(value))

print("output:", new_list)